### ISSUE TITLE
AUTH48 TODO-tracker

### ISSUE THREAD

**Issue by obgm** [ace-wg/ace-dtls-profile#31]
This issue is used to keep an updated list of TODOs in the AUTH48 process.
The edited XML is currently in [auth48/rfc9202.xml](../blob/master/auth48/rfc9202.xml).

* [x] Content review
   - [x] IANA considerations
   - [x] contact information
   - [x] references
* [x] Copyright notices and legends
* [x] Semantic markup
   - [x] `<tt>` vs. quotes ~~(TBD)~~
   - [x] `artwork` and `sourcecode`
* [x] Formatted output
